"""updated question table

Revision ID: 79fc592752dc
Revises: cd54400b1ab2
Create Date: 2025-01-31 19:28:00.094743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79fc592752dc'
down_revision = 'cd54400b1ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('options')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
