"""lets see.

Revision ID: 873a9bb4c00d
Revises: c20dd7f19663
Create Date: 2025-01-31 07:47:23.059978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873a9bb4c00d'
down_revision = 'c20dd7f19663'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
