"""updated question table

Revision ID: cd54400b1ab2
Revises: 873a9bb4c00d
Create Date: 2025-01-31 18:59:00.435111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd54400b1ab2'
down_revision = '873a9bb4c00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('options', sa.JSON(), nullable=False))
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('options')

    # ### end Alembic commands ###
